batch_size:
  value: 100
beta_1:
  value: 0.22693882275467836
beta_2:
  value: 0.999
chi_frequency:
  value: 5
clipnorm:
  value: null
complexity_0:
  value: 1
complexity_1:
  value: 1
complexity_2:
  value: 2
d_layers:
  value:
  - 64
  - 128
  - 256
dropout:
  value: 0.44053850596844424
ema_momentum:
  value: 0.9
ema_overwrite_frequency:
  value: 1
g_layers:
  value:
  - 25600
  - 512
  - 256
global_clipnorm:
  value: null
lambda_:
  value: 0.005844921623203759
latent_dims:
  value: 100
learning_rate:
  value: 0.00013367626823798716
lrelu:
  value: 0.2991161912395133
nepochs:
  value: 200
seed:
  value: 7
train_size:
  value: 1000
training_balance:
  value: 2
true_label_smooth:
  value: 0.9
use_ema:
  value: false
