[project]
name = "hazGAN"
version = "2.0.2"
# license = { file = "LICENSE" }
description = "Deep generative modelling for compound hazard sampling."
readme = "README.md"
authors = [
    { name = "Alison Peard", email = "alison.peard@ouce.ox.ac.uk" },
]
maintainers = [{ name = "Alison Peard", email = "alison.peard@ouce.ox.ac.uk" }]
classifiers = [
    "Private :: Do Not Upload",
    "Development Status :: 2 - Pre-Alpha",
    "Intended Audience :: Science/Research",
    # "License :: OSI Approved :: MIT License",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Topic :: Scientific/Engineering :: Artificial Intelligence"
]
keywords = []
requires-python = ">=3.8"
dependencies = [
    "geopandas",
    "matplotlib",
    "numpy",
    "openpyxl",
    "pandera",
    "pyarrow",
    "pyogrio",
    "igraph",
    "rasterio",
    "shapely",
    "scipy"
]

