wandb_version: 1

augment_policy:
  value: color
batch_size:
  value: 64
beta_1:
  value: 0.5736980637309157
beta_2:
  value: 0.9393862173346356
channel_multiplier:
  value: 4
critic_width:
  value: 256
dropout:
  value: 0
ema_momentum:
  value: 0.9497454103879122
embedding_depth:
  value: 32
epochs:
  value: 600
fields:
  value:
  - u10
generator_width:
  value: 64
input_policy:
  value: add
lambda_gp:
  value: 5
latent_dims:
  value: 128
lookahead:
  value: false
lrelu:
  value: 0.2
noise_sd:
  value: 0.01
pretrain_size:
  value: 10000
target_weights:
  value:
  - 0
  - 0.4
  - 0.6
training_balance:
  value: 10
use_ema:
  value: true
warmup_steps:
  value: 0.01
weight_decay:
  value: 0
