wandb_version: 1

seed:
  desc: null
  value: 75
filter_size:
  desc: null
  value: 3
_wandb:
  desc: null
  value:
    code_path: code/scripts/model_fitting/mfe/train.py
    python_version: 3.10.13
    cli_version: 0.16.6
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1719938170.0
    t:
      1:
      - 55
      2:
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.10.13
      5: 0.16.6
      8:
      - 4
      - 5
      13: darwin-arm64
