wandb_version: 1

_wandb:
  desc: null
  value:
    code_path: code/scripts/training/train.py
    python_version: 3.10.13
    cli_version: 0.16.6
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1727702350.0
    t:
      1:
      - 2
      - 3
      - 54
      - 55
      3:
      - 23
      4: 3.10.13
      5: 0.16.6
      8:
      - 5
      13: darwin-arm64
